title: Hamood's Data Dispatch
description: Hamood.net
author: Hamood Aleem

url: "https://hamood.net"
baseurl: ""

remote_theme: jekyll/minima@1e8a445

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
